#!/bin/sh
set -eo pipefail

usage() {
      echo "Usage: $0 (-r <release> | -p <preview> | -v <preview-verison>)  -c <location of cloud specific install-config.yaml> -d <install dir> -n <network config> [-x] <first delete the specified cluster>"
}

exit_error() {
  usage
  exit 1
}

if [ -z "$INSTALLER_BIN" ]; then
    echo "missing INSTALLER_BIN environment variable"
    exit_error
fi

delete=0
while getopts "r:p:v:c:d:n:x" opt; do
  case ${opt} in
    r ) # specify an OpenShift <release> from https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/
      release=https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/$OPTARG
      ;;
    p ) # specify an OpenShift CI stream from https://openshift-release.apps.ci.l2s4.p1.openshiftapps.com/. Ex: 4.14.0-0.ci
      preview=$(curl -s https://openshift-release.apps.ci.l2s4.p1.openshiftapps.com/api/v1/releasestream/$OPTARG/latest | jq '.pullSpec')
      preview=${preview%\"}
      preview=${preview#*:}
      ;;
    v ) # specify a OpenShift CI stream version from https://openshift-release.apps.ci.l2s4.p1.openshiftapps.com/. Ex: 4.14.0-0.ci-2023-03-20-081138
      preview=$OPTARG
      ;;
    c ) # cloud specific install-config.yaml
      if [ -d $OPTARG ]; then
        echo "-c $OPTARG cannot be a directory"
        exit 1
      fi
      config=$OPTARG
      ;;
    d ) # cluster installation dir
      if [ ! -d $OPTARG ]; then
        echo "-d $OPTARG cannot be a file"
        exit 1
      fi
      clusterdir=$OPTARG
      ;;
    n ) # cluster-network-03-config.yml or calico manifest directory
      networkconfig=$OPTARG
      ;;
    x ) # delete the cluster before creation
      delete=1
      ;;
    \? )
      usage
      exit 0
      ;;
    : )
      echo "Invalid option: ${OPTARG} requires an argument" 1>&2
      exit_error
      ;;
    * )
      echo "Invalid option: ${OPTARG}" 1>&2
      exit_error
      ;;
  esac
done

bindir=$INSTALLER_BIN

if [ -z "$release" -a -z "$preview" ]; then
    if [ ! -f $bindir/openshift-install ]; then
      echo "missing openshift-install. specify -r or -p or -v to ensure $bindir/openshift-install exists"
      error exit
    fi
fi

if [ -z "$config" ]; then
    echo "missing -c option"
    exit_error
fi

if [ -z "$clusterdir" ]; then
    echo "missing -d option"
    exit_error
fi

pushd $bindir
if [ -n "$release" ]; then
    echo "Using $release"
    curl ${release}/openshift-install-linux.tar.gz | tar -zx openshift-install
elif [ -n "$preview" ]; then
    echo "Using $preview"
    oc adm release extract --command=openshift-install registry.ci.openshift.org/ocp/release:$preview
    oc adm release extract --command=oc registry.ci.openshift.org/ocp/release:$preview
fi

${bindir}/openshift-install version

installcmd="${bindir}/openshift-install --dir=${clusterdir} "

if [ "$delete" -eq "1" ]; then
    $installcmd destroy cluster
fi

rm -rf $clusterdir/*
cp $config $clusterdir

echo $version > $clusterdir/version

if [ "$networkconfig" ]; then
    $installcmd create manifests
    cp $networkconfig $clusterdir/manifests/cluster-network-03-config.yml
fi

$installcmd create cluster

popd
